# .github/dependabot.yml
version: 2
updates:
  # 如果未来在 /site_realtime_full 下使用 NPM
  - package-ecosystem: "npm"
    directory: "/site_realtime_full"
    schedule:
      interval: "weekly"
    groups:
      security-fixes:
        applies-to: security-updates
        patterns: ["*"]

  # 同时监控 GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
